production:
  primary:
    <<: *default
    url: "<%= ENV['DATABASE_URL'].presence || 'mysql2://localhost/placeholder' %>"
  cache:
    <<: *default
    url: "<%= ENV['DATABASE_URL'].presence || 'mysql2://localhost/placeholder' %>"
  queue:
    <<: *default
    url: "<%= ENV['DATABASE_URL'].presence || 'mysql2://localhost/placeholder' %>"
  cable:
    <<: *default
    url: "<%= ENV['DATABASE_URL'].presence || 'mysql2://localhost/placeholder' %>"