service: store
image: justink33/linknest

servers:
  web:
    hosts:
      - 54.89.195.68
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: true
  job:
    hosts:
      - 54.89.195.68
    cmd: bin/jobs
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: false
        JOB_CONCURRENCY: 3

registry:
  server: ghcr.io
  username: JustinK33
  password:
    - GHCR_TOKEN

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "store_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ec2-user
  keys:
    - ~/.ssh/linknest.pem