# Name of your application. Used to uniquely configure containers.
service: store

# Name of the container image (use your-user/app-name on external registries).
image: justink33/linknest

# Deploy to these servers.
servers:
  web:
    hosts:
      - 54.89.195.68
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: true
  job:
    hosts:
      - 54.89.195.68
    cmd: bin/jobs
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: false
        JOB_CONCURRENCY: 3

registry:
  server: ghcr.io
  username: JustinK33
  password:
    - GHCR_TOKEN

env:
  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "store_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64